### ISSUE TITLE
mobilraker

### ISSUE THREAD

**Issue by m4sis** [Jpe230/SonicPad-Debian#21]
impossible to install mobil raker

` ERROR: Command errored out with exit status 1:
   command: /home/sonic/mobileraker-env/bin/python -u -c 'import sys, setuptools                                                                  , tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b                                                                  8c1e36bb798853b0/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lknrsssw/pillow_2                                                                  82dc55e78d0422b8c1e36bb798853b0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'                                                                  , open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();                                                                  exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6ni                                                                  5qg1g
       cwd: /tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/
`
`
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "/tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/se                                                                  tup.py", line 993, in <module>
        setup(
      File "/home/sonic/mobileraker-env/lib/python3.9/site-packages/setuptools/_                                                                  _init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/sonic/mobileraker-env/lib/python3.9/site-packages/setuptools/c                                                                  ommand/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.9/distutils/command/install.py", line 590, in run
        self.run_command('build')
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/sonic/mobileraker-env/lib/python3.9/site-packages/setuptools/c                                                                  ommand/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/se                                                                  tup.py", line 809, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/se                                                                  tup.py", line 1010, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/sonic/mobileraker-env/bin/p                                                                  ython -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-insta                                                                  ll-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/setup.py'"'"'; __file__='"'"                                                                  '/tmp/pip-install-lknrsssw/pillow_282dc55e78d0422b8c1e36bb798853b0/setup.py'"'"'                                                                  ;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'                                                                  \r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))                                                                  ' install --record /tmp/pip-record-o2xawx2v/install-record.txt --single-version-                                                                  externally-managed --compile --install-headers /home/sonic/mobileraker-env/inclu                                                                  de/site/python3.9/Pillow Check the logs for full command output.

#=======================================================#
 Mobileraker's companion installation failed!
`

**Comment by m4sis** [comment]
ok i'll go try that thank you

**Comment by m4sis** [comment]
Thanks it works
